locale = "en"
label = "English"
direction = "ltr"
weight = 1

title = "Matheo's blog"

[params]
  dateFormat = "2 January 2006"
  description = "A blog about building things with code and computers"
  mainSections = ["posts"]

[params.author]
  name = "Matheo"
  image = "img/profile.jpg"
  headline = "Thanks for stopping by."
  bio = "👋 French software engineer and Epitech student. Builder of ZamSync. I like tinkering with computers and playing chess."
  links = [
    { github = "https://github.com/Etoile-Bleu" },
    { linkedin = "https://www.linkedin.com/in/math%C3%A9o-delbarre/" }
  ]
